// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<flua_State Function()>()
external flua_State flua_create();

@ffi.Native<ffi.Void Function(flua_State)>()
external void flua_close(flua_State state);

@ffi.Native<ffi.Int Function(flua_State, ffi.Pointer<ffi.Char>)>()
external int flua_do_string(flua_State state, ffi.Pointer<ffi.Char> code);

@ffi.Native<ffi.Void Function(flua_State, ffi.Pointer<ffi.Char>)>()
external void flua_set_global(flua_State state, ffi.Pointer<ffi.Char> name);

@ffi.Native<ffi.Void Function(flua_State, ffi.Pointer<ffi.Char>, ffi.Int64)>()
external void flua_set_global_int(
  flua_State state,
  ffi.Pointer<ffi.Char> name,
  int value,
);

@ffi.Native<ffi.Void Function(flua_State, ffi.Pointer<ffi.Char>, ffi.Double)>()
external void flua_set_global_double(
  flua_State state,
  ffi.Pointer<ffi.Char> name,
  double value,
);

@ffi.Native<
  ffi.Void Function(flua_State, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external void flua_set_global_string(
  flua_State state,
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Char> value,
);

@ffi.Native<ffi.Void Function(flua_State, ffi.Pointer<ffi.Char>, ffi.Int)>()
external void flua_set_global_bool(
  flua_State state,
  ffi.Pointer<ffi.Char> name,
  int value,
);

@ffi.Native<ffi.Void Function(flua_State, ffi.Pointer<ffi.Char>)>()
external void flua_set_global_nil(flua_State state, ffi.Pointer<ffi.Char> name);

@ffi.Native<ffi.Void Function(flua_State, ffi.Int64)>()
external void flua_push_int(flua_State state, int value);

@ffi.Native<ffi.Void Function(flua_State, ffi.Double)>()
external void flua_push_double(flua_State state, double value);

@ffi.Native<ffi.Void Function(flua_State, ffi.Pointer<ffi.Char>)>()
external void flua_push_string(flua_State state, ffi.Pointer<ffi.Char> value);

@ffi.Native<ffi.Void Function(flua_State, ffi.Int)>()
external void flua_push_bool(flua_State state, int value);

@ffi.Native<ffi.Void Function(flua_State)>()
external void flua_push_nil(flua_State state);

@ffi.Native<ffi.Void Function(flua_State)>()
external void flua_new_table(flua_State state);

@ffi.Native<ffi.Void Function(flua_State, ffi.Int, ffi.Int)>()
external void flua_create_table(flua_State state, int narray, int nrec);

@ffi.Native<ffi.Void Function(flua_State, ffi.Int, ffi.Pointer<ffi.Char>)>()
external void flua_set_field(
  flua_State state,
  int idx,
  ffi.Pointer<ffi.Char> name,
);

@ffi.Native<ffi.Void Function(flua_State, ffi.Int)>()
external void flua_set_table(flua_State state, int idx);

@ffi.Native<ffi.Void Function(flua_State, ffi.Int)>()
external void flua_raw_set(flua_State state, int idx);

@ffi.Native<ffi.Void Function(flua_State, ffi.Int, ffi.Int64)>()
external void flua_set_i(flua_State state, int idx, int n);

@ffi.Native<ffi.Void Function(flua_State, ffi.Int, ffi.Int64)>()
external void flua_raw_set_i(flua_State state, int idx, int n);

/// TODO: flua_push_function - generic c function that calls dart?
@ffi.Native<ffi.Int Function(flua_State, ffi.Pointer<ffi.Char>)>()
external int flua_get_global_type(flua_State state, ffi.Pointer<ffi.Char> name);

@ffi.Native<ffi.Int64 Function(flua_State, ffi.Pointer<ffi.Char>)>()
external int flua_get_global_int(flua_State state, ffi.Pointer<ffi.Char> name);

@ffi.Native<ffi.Double Function(flua_State, ffi.Pointer<ffi.Char>)>()
external double flua_get_global_double(
  flua_State state,
  ffi.Pointer<ffi.Char> name,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(flua_State, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> flua_get_global_string(
  flua_State state,
  ffi.Pointer<ffi.Char> name,
);

@ffi.Native<ffi.Int Function(flua_State, ffi.Pointer<ffi.Char>)>()
external int flua_get_global_bool(flua_State state, ffi.Pointer<ffi.Char> name);

@ffi.Native<ffi.Int Function(flua_State, ffi.Pointer<ffi.Char>)>()
external int flua_get_global(flua_State state, ffi.Pointer<ffi.Char> name);

@ffi.Native<ffi.Int Function(flua_State, ffi.Int)>()
external int flua_get_table(flua_State state, int idx);

@ffi.Native<ffi.Int Function(flua_State, ffi.Int)>()
external int flua_raw_get(flua_State state, int idx);

@ffi.Native<ffi.Int Function(flua_State, ffi.Int, ffi.Int64)>()
external int flua_get_i(flua_State state, int idx, int n);

@ffi.Native<ffi.Int Function(flua_State, ffi.Int, ffi.Int64)>()
external int flua_raw_get_i(flua_State state, int idx, int n);

@ffi.Native<ffi.Int Function(flua_State, ffi.Pointer<ffi.Char>)>()
external int flua_prepare_pcall(
  flua_State state,
  ffi.Pointer<ffi.Char> func_name,
);

@ffi.Native<ffi.Int Function(flua_State, ffi.Int)>()
external int flua_pcall(flua_State state, int arg_count);

@ffi.Native<ffi.Int64 Function(flua_State, ffi.Int)>()
external int flua_to_integer(flua_State state, int index);

@ffi.Native<ffi.Double Function(flua_State, ffi.Int)>()
external double flua_to_number(flua_State state, int index);

@ffi.Native<ffi.Pointer<ffi.Char> Function(flua_State, ffi.Int)>()
external ffi.Pointer<ffi.Char> flua_to_string(flua_State state, int index);

@ffi.Native<ffi.Int Function(flua_State, ffi.Int)>()
external int flua_to_boolean(flua_State state, int index);

@ffi.Native<ffi.Pointer<ffi.Char> Function(flua_State)>()
external ffi.Pointer<ffi.Char> flua_error(flua_State state);

@ffi.Native<ffi.Int Function(flua_State)>()
external int flua_gettop(flua_State state);

@ffi.Native<ffi.Void Function(flua_State, ffi.Int)>()
external void flua_pop(flua_State state, int n);

@ffi.Native<ffi.Void Function(flua_State, ffi.Int)>()
external void flua_set_top(flua_State state, int idx);

@ffi.Native<ffi.Int Function(flua_State, ffi.Int)>()
external int flua_type(flua_State state, int idx);

@ffi.Native<ffi.Int Function(flua_State, ffi.Int)>()
external int flua_next(flua_State state, int idx);

@ffi.Native<ffi.Int Function(flua_State, ffi.Int)>()
external int flua_ref(flua_State state, int idx);

@ffi.Native<ffi.Void Function(flua_State, ffi.Int, ffi.Int)>()
external void flua_unref(flua_State state, int idx, int ref);

@ffi.Native<ffi.Int>()
external int FLUA_TNONE;

@ffi.Native<ffi.Int>()
external int FLUA_TNIL;

@ffi.Native<ffi.Int>()
external int FLUA_TBOOLEAN;

@ffi.Native<ffi.Int>()
external int FLUA_TLIGHTUSERDATA;

@ffi.Native<ffi.Int>()
external int FLUA_TNUMBER;

@ffi.Native<ffi.Int>()
external int FLUA_TSTRING;

@ffi.Native<ffi.Int>()
external int FLUA_TTABLE;

@ffi.Native<ffi.Int>()
external int FLUA_TFUNCTION;

@ffi.Native<ffi.Int>()
external int FLUA_TUSERDATA;

@ffi.Native<ffi.Int>()
external int FLUA_TTHREAD;

@ffi.Native<ffi.Int>()
external int FLUA_REGISTRYINDEX;

typedef flua_State = ffi.Pointer<ffi.Void>;
